// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQllN-AxD3tNX6vDJ-8pH7bd6NEzV3A4',
    appId: '1:472231957714:web:5858942f90fddcd6d3c90b',
    messagingSenderId: '472231957714',
    projectId: 'whatsapp-byocean',
    authDomain: 'whatsapp-byocean.firebaseapp.com',
    storageBucket: 'whatsapp-byocean.appspot.com',
    measurementId: 'G-175N3NVRN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeeMg2iQ6_AFwZlKdt_L0yzj_aX5xDXOI',
    appId: '1:472231957714:android:d883e0389f32d292d3c90b',
    messagingSenderId: '472231957714',
    projectId: 'whatsapp-byocean',
    storageBucket: 'whatsapp-byocean.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKb_FDFUBiznl0m9RcxfSFLt3sk01nWc',
    appId: '1:472231957714:ios:d8fe9ae563fbf8d5d3c90b',
    messagingSenderId: '472231957714',
    projectId: 'whatsapp-byocean',
    storageBucket: 'whatsapp-byocean.appspot.com',
    iosClientId: '472231957714-n6refcd9evveafr592s69use2pdn7ukm.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRKb_FDFUBiznl0m9RcxfSFLt3sk01nWc',
    appId: '1:472231957714:ios:568cb36c02e7dd7ad3c90b',
    messagingSenderId: '472231957714',
    projectId: 'whatsapp-byocean',
    storageBucket: 'whatsapp-byocean.appspot.com',
    iosClientId: '472231957714-jml73drqvvebbe9d38mdu9l0uidgok51.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
